// <auto-generated />
namespace Branch.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class FixedemptyServiceTags : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixedemptyServiceTags));
        
        string IMigrationMetadata.Id
        {
            get { return "201410262140311_Fixed empty ServiceTags"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
